wandb_version: 1

model_name:
  desc: null
  value: TSKM
data_dir:
  desc: null
  value: data/MIMIC/processed
time_window:
  desc: null
  value:
  - 0
  - 10
feat_subset:
  desc: null
  value: vitals-static
train_test_ratio:
  desc: null
  value: 0.6
train_val_ratio:
  desc: null
  value: 0.6
seed:
  desc: null
  value: 3535
normalize:
  desc: null
  value: true
num_folds:
  desc: null
  value: 1
model_params:
  desc: null
  value:
    window_num_obvs: 4
    K: 6
    latent_dim: 32
    n_fwd_blocks: 1
    dropout: 0.5
training_params:
  desc: null
  value:
    batch_size: 32
    num_epochs: 100
    lr: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1695815198.882047
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.9.0
      5: 0.15.4
      8:
      - 1
      - 3
      - 5
