wandb_version: 1

data_dir:
  desc: null
  value: data/MIMIC/processed
time_window:
  desc: null
  value:
  - 0
  - 10
feat_subset:
  desc: null
  value: vitals-static
train_test_ratio:
  desc: null
  value: 0.6
train_val_ratio:
  desc: null
  value: 0.6
seed:
  desc: null
  value: 1313
normalize:
  desc: null
  value: true
num_folds:
  desc: null
  value: 1
model_params:
  desc: null
  value:
    K: 10
    latent_dim: 30
    gate_num_hidden_layers: 2
    gate_num_hidden_nodes: 20
    bias: true
    dropout: 0.5
    device: cpu
    seed: 1313
    K_fold_idx: 1
train_params:
  desc: null
  value:
    lr: 0.001
    batch_size: 64
    num_epochs: 5
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1695935975.891065
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.0
      5: 0.15.4
      8:
      - 1
      - 3
      - 5
