wandb_version: 1

run_name:
  desc: null
  value: test-3
data_config:
  desc: null
  value:
    data_name: MIMIC
    target_window: 48
    feat_set: vit-sta
    time_range:
    - 0
    - 10
    train_test_ratio: 0.6
    train_val_ratio: 0.4
    seed: 2323
model_config:
  desc: null
  value:
    i_size: 9
    o_size: 4
    w_size: 3
    K: 10
    l_size: 16
    gate_hidden_l: 2
    gate_hidden_n: 20
    seed: 2323
training_config:
  desc: null
  value:
    lr: 0.001
    num_epochs: 5
    batch_size: 128
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686708126.433562
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.9.0
      5: 0.15.4
      8:
      - 3
      - 5
    visualize:
      1/Precision_Recall:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: recall
            y: precision
            class: class
          stringSettings:
            title: Precision v. Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 1/Precision_Recall_table
                fields: []
      1/Receiver_Operating_Char:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: fpr
            y: tpr
            class: class
          stringSettings:
            title: ROC
            x-axis-title: False positive rate
            y-axis-title: True positive rate
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 1/Receiver_Operating_Char_table
                fields: []
      2/Precision_Recall:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: recall
            y: precision
            class: class
          stringSettings:
            title: Precision v. Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 2/Precision_Recall_table
                fields: []
      2/Receiver_Operating_Char:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: fpr
            y: tpr
            class: class
          stringSettings:
            title: ROC
            x-axis-title: False positive rate
            y-axis-title: True positive rate
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 2/Receiver_Operating_Char_table
                fields: []
      3/Precision_Recall:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: recall
            y: precision
            class: class
          stringSettings:
            title: Precision v. Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 3/Precision_Recall_table
                fields: []
      3/Receiver_Operating_Char:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: fpr
            y: tpr
            class: class
          stringSettings:
            title: ROC
            x-axis-title: False positive rate
            y-axis-title: True positive rate
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 3/Receiver_Operating_Char_table
                fields: []
      4/Precision_Recall:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: recall
            y: precision
            class: class
          stringSettings:
            title: Precision v. Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 4/Precision_Recall_table
                fields: []
      4/Receiver_Operating_Char:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: fpr
            y: tpr
            class: class
          stringSettings:
            title: ROC
            x-axis-title: False positive rate
            y-axis-title: True positive rate
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 4/Receiver_Operating_Char_table
                fields: []
      5/Precision_Recall:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: recall
            y: precision
            class: class
          stringSettings:
            title: Precision v. Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 5/Precision_Recall_table
                fields: []
      5/Receiver_Operating_Char:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: fpr
            y: tpr
            class: class
          stringSettings:
            title: ROC
            x-axis-title: False positive rate
            y-axis-title: True positive rate
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: 5/Receiver_Operating_Char_table
                fields: []
